Practica1/Areas/Admin/Controllers/BodegaController.cs
using Microsoft.AspNetCore.Mvc;
using Practica1.AccesoDatos.Repositorio.IRepositorio;
using Practica1.Modelos;
using Practica1.Utilidades;

namespace Practica1.Areas.Admin.Controllers
{
    [Area("admin")]
    public class BodegaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        public BodegaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo= unidadTrabajo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Bodega bodega = new Bodega();
            if (id == null)
            {
                //Crear nueva bodega
                bodega.Estado = true;
                return View(bodega);
            }
            bodega = await _unidadTrabajo.Bodega.obtener(id.GetValueOrDefault()); //Nos aseguramos que la información llegue correctamente
            if (bodega == null)
            {
                return NotFound();
            }
            return View(bodega);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //Evita que se pueda clonar 
        public async Task<IActionResult> Upsert(Bodega bodega)
        {
            if (ModelState.IsValid)
            {
                if (bodega.Id == 0)
                {
                    await _unidadTrabajo.Bodega.Agregar(bodega);
                    TempData[DS.Exitosa] = "Bodega creada exitósamente";
                }
                else
                {
                    _unidadTrabajo.Bodega.Actualizar(bodega);
                    TempData[DS.Exitosa] = "Bodega actualizada exitósamente";
                }
                await _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al guardar la bodega";
            return View(bodega);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var bodegaDB = await _unidadTrabajo.Bodega.obtener(id);
            if (bodegaDB == null)
            {
                return Json(new { success = false, message = "Error al borrar Bodega." });
            }
            _unidadTrabajo.Bodega.Remover(bodegaDB);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Bodega borrada exitósamente." });
        }

        #region API 
        [HttpGet]
        public async Task<IActionResult> obtenerTodos()
        {
            var todos = await _unidadTrabajo.Bodega.obtenerTodos();
            return Json(new { data = todos });
        }

        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Bodega.obtenerTodos();
            if (id == 0)
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);
            }
            if (valor)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        #endregion
    }
}

Practica1/Areas/Admin/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Practica1.AccesoDatos.Repositorio.IRepositorio;
using Practica1.Modelos;
using Practica1.Utilidades;

namespace Practica1.Areas.Admin.Controllers
{
    [Area("admin")]
    public class CategoriaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        public CategoriaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo= unidadTrabajo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Categoria categoria = new Categoria();
            if (id == null)
            {
                //Crear nueva categoria
                categoria.Estado = true;
                return View(categoria);
            }
            categoria = await _unidadTrabajo.Categoria.obtener(id.GetValueOrDefault()); //Nos aseguramos que la información llegue correctamente
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //Evita que se pueda clonar 
        public async Task<IActionResult> Upsert(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                if (categoria.Id == 0)
                {
                    await _unidadTrabajo.Categoria.Agregar(categoria);
                    TempData[DS.Exitosa] = "Categoria creada exitósamente";
                }
                else
                {
                    _unidadTrabajo.Categoria.Actualizar(categoria);
                    TempData[DS.Exitosa] = "Categoria actualizada exitósamente";
                }
                await _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al guardar la categoria";
            return View(categoria);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var categoriaDB = await _unidadTrabajo.Categoria.obtener(id);
            if (categoriaDB == null)
            {
                return Json(new { success = false, message = "Error al borrar Categoria." });
            }
            _unidadTrabajo.Categoria.Remover(categoriaDB);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Categoria borrada exitósamente." });
        }

        #region API 
        [HttpGet]
        public async Task<IActionResult> obtenerTodos()
        {
            var todos = await _unidadTrabajo.Categoria.obtenerTodos();
            return Json(new { data = todos });
        }

        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Categoria.obtenerTodos();
            if (id == 0)
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);
            }
            if (valor)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        #endregion
    }
}

Practica1/Areas/Admin/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;
using Practica1.AccesoDatos.Repositorio.IRepositorio;
using Practica1.Modelos;
using Practica1.Utilidades;

namespace Practica1.Areas.Admin.Controllers
{
    [Area("admin")]
    public class DepartamentoController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        public DepartamentoController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo= unidadTrabajo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Departamento departamento = new Departamento();
            if (id == null)
            {
                //Crear nueva categoria
                return View(departamento);
            }
            departamento = await _unidadTrabajo.Departamento.obtener(id.GetValueOrDefault()); //Nos aseguramos que la información llegue correctamente
            if (departamento == null)
            {
                return NotFound();
            }
            return View(departamento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //Evita que se pueda clonar 
        public async Task<IActionResult> Upsert(Departamento departamento)
        {
            if (ModelState.IsValid)
            {
                if (departamento.Id == 0)
                {
                    await _unidadTrabajo.Departamento.Agregar(departamento);
                    TempData[DS.Exitosa] = "departamento creada exitósamente";
                }
                else
                {
                    _unidadTrabajo.Departamento.Actualizar(departamento);
                    TempData[DS.Exitosa] = "departamento actualizada exitósamente";
                }
                await _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al guardar el departamento";
            return View(departamento);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var departamentoDB = await _unidadTrabajo.Departamento.obtener(id);
            if (departamentoDB == null)
            {
                return Json(new { success = false, message = "Error al borrar Departamento." });
            }
            _unidadTrabajo.Departamento.Remover(departamentoDB);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Departamento borrada exitósamente." });
        }

        #region API 
        [HttpGet]
        public async Task<IActionResult> obtenerTodos()
        {
            var todos = await _unidadTrabajo.Departamento.obtenerTodos();
            return Json(new { data = todos });
        }

        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Departamento.obtenerTodos();
            if (id == 0)
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);
            }
            if (valor)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        #endregion
    }
}

Practica1/Areas/Admin/Controllers/MarcaController.cs
using Microsoft.AspNetCore.Mvc;
using Practica1.AccesoDatos.Repositorio.IRepositorio;
using Practica1.Modelos;
using Practica1.Utilidades;

namespace Practica1.Areas.Admin.Controllers
{
    [Area("admin")]
    public class MarcaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;
        public MarcaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo= unidadTrabajo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Marca marca = new Marca();
            if (id == null)
            {
                //Crear nueva marca
                marca.Estado = true;
                return View(marca);
            }
            marca = await _unidadTrabajo.Marca.obtener(id.GetValueOrDefault()); //Nos aseguramos que la información llegue correctamente
            if (marca == null)
            {
                return NotFound();
            }
            return View(marca);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //Evita que se pueda clonar 
        public async Task<IActionResult> Upsert(Marca marca)
        {
            if (ModelState.IsValid)
            {
                if (marca.Id == 0)
                {
                    await _unidadTrabajo.Marca.Agregar(marca);
                    TempData[DS.Exitosa] = "Marca creada exitósamente";
                }
                else
                {
                    _unidadTrabajo.Marca.Actualizar(marca);
                    TempData[DS.Exitosa] = "Marca actualizada exitósamente";
                }
                await _unidadTrabajo.Guardar();
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al guardar la Marca";
            return View(marca);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var marcaDB = await _unidadTrabajo.Marca.obtener(id);
            if (marcaDB == null)
            {
                return Json(new { success = false, message = "Error al borrar Marca." });
            }
            _unidadTrabajo.Marca.Remover(marcaDB);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Marca borrada exitósamente." });
        }

        #region API 
        [HttpGet]
        public async Task<IActionResult> obtenerTodos()
        {
            var todos = await _unidadTrabajo.Marca.obtenerTodos();
            return Json(new { data = todos });
        }

        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Marca.obtenerTodos();
            if (id == 0)
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
            }
            else
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);
            }
            if (valor)
            {
                return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        #endregion
    }
}

Practica1/Views/Shared/_BotonesActualizarYRegresar.cshtml
@model int
<div class="d-grid gap-2 d-md-block">
	<button type="submit" class="btn btn-primary" onfocus="false" asp-route-id="@Model">
		<i class="bi bi-clipboard-plus-fill"></i>Actualizar
	</button>
	<a asp-action="Index"><i class="bi bi-arrow-return-left"></i>Regresar</a>
</div>

Practica1/Views/Shared/_BotonesCrearYRegresar.cshtml
<div class="d-grid gap-2 d-md-block">
	<button type="submit" class="btn btn-primary" onfocus="false">
		<i class="bi bi-clipboard-plus-fill"></i>Crear
	</button>

	<button type="submit" class="btn btn-secondary">
		<a asp-action="Index"><i class="bi bi-arrow-return-left"></i>Regresar</a>
	</button>
</div>

Practica1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practica1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practica1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Contenido
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Bodega" asp-action="Index">Bodega</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Categoria" asp-action="Index">Categoria</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Marca" asp-action="Index">Marca</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Producto" asp-action="Index">Producto</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Departamento" asp-action="Index">Departamento</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Profesor" asp-action="Index">Profesor</a>
                                    <a class="nav-link text-dark" asp-area="Admin" asp-controller="Curso" asp-action="Index">Curso</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notificaciones" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Practica1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Practica1/Views/Shared/_Notificaciones.cshtml
@using Practica1.Utilidades

@if (TempData[DS.Exitosa] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.success('@TempData[DS.Exitosa]');
	</script>
}

@if (TempData[DS.Error] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script type="text/javascript">
		toastr.error('@TempData[DS.Error]');
	</script>
}